---
# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'silly'

# One of value-only, full
#    value-only - converts any known group addresses to its value
#    full - a json object containing value. Additionally also name and unit type for known group addresses.
messageType: full

# Ignore unknown group addresses
ignoreUnknownGroupAddresses: false

knx:
  # ETS exported group addresses
  etsExport: 'knx.xml'

  # Configuration passed to the KNX library
  options:
    # IP address of your Ethernet-KNX interface
    ipAddr: '10.1.1.220'
    # KNX physical address we'd like to use
    physAddr: '15.15.15'

influx:
  # URL to MQTT broker
  host: 'influxdb'
  database: 'knx'
  measurement: 'knx'
